// src/content/articlesData.js
export const articles = [
  {
    slug: "tech-behind-disposable-emails",
    title: "The Tech Behind Disposable Emails",
    description: "Understand how disposable email services work under the hood — from SMTP servers to privacy-first ephemeral storage.",
    date: "2026-03-10",
    readTime: "5 min read",
    category: "Technology",
    categoryColor: "primary",
    icon: "bi-cpu",
    tags: ["SMTP", "privacy", "infrastructure"],
  },
  {
    slug: "receive-sms-otp-online",
    title: "How to Receive SMS OTP Verification Online",
    description: "Discover safe and reliable methods to receive OTPs online without exposing your personal phone number.",
    date: "2026-03-18",
    readTime: "4 min read",
    category: "Privacy",
    categoryColor: "success",
    icon: "bi-shield-lock",
    tags: ["OTP", "SMS", "verification"],
  },
  {
    slug: "private-domains-temp-email",
    title: "Private Domains: Get Your Own Temporary Email",
    description: "Learn how to set up a private custom domain for disposable email and take full control of your online identity.",
    date: "2026-04-02",
    readTime: "6 min read",
    category: "Guide",
    categoryColor: "info",
    icon: "bi-globe2",
    tags: ["domain", "custom email", "setup"],
  },
  {
    slug: "burner-email-for-social-media",
    title: "Why You Need a Burner Email for Social Media",
    description: "Protect your digital identity and stop spam by using burner emails when signing up on social platforms.",
    date: "2026-04-10",
    readTime: "3 min read",
    category: "Security",
    categoryColor: "warning",
    icon: "bi-incognito",
    tags: ["social media", "spam", "anonymity"],
  },
];
