// src/content/articlesData.js
const articleCatalog = [
  {
    slug: "temp-email-for-newsletters",
    title: "Managing Email Subscriptions: Temporary Email for Newsletters",
    description: "Keep your inbox organized by using temporary email for single newsletters, experimental subscriptions, and content you might not keep.",
    date: "2026-04-05",
    readTime: "6 min read",
    category: "Guide",
    categoryColor: "primary",
    icon: "bi-envelope-open",
    tags: ["newsletters", "spam", "subscriptions", "organization"],
  },
  {
    slug: "temp-email-for-gaming-accounts",
    title: "Temporary Email for Gaming Accounts: Protect Your Game Library",
    description: "Use temporary email for gaming alt accounts, beta testing, and privacy-conscious gaming without losing access to your main library.",
    date: "2026-04-06",
    readTime: "7 min read",
    category: "Privacy",
    categoryColor: "success",
    icon: "bi-gamepad2",
    tags: ["gaming", "alts", "privacy", "verification"],
  },
  {
    slug: "temp-email-for-dating-apps",
    title: "Stay Safe on Dating Apps: Use Temporary Email",
    description: "Protect your privacy on dating apps and dating sites by using temporary email to control your digital footprint.",
    date: "2026-04-07",
    readTime: "6 min read",
    category: "Security",
    categoryColor: "warning",
    icon: "bi-heart",
    tags: ["dating", "privacy", "security", "anonymity"],
  },
  {
    slug: "temp-email-for-account-testing",
    title: "Temporary Email for QA Testing and Account Testing",
    description: "Use disposable email addresses for software QA, user testing, and development workflows without cluttering your inbox.",
    date: "2026-04-08",
    readTime: "7 min read",
    category: "Technology",
    categoryColor: "primary",
    icon: "bi-bug",
    tags: ["testing", "development", "QA", "automation"],
  },
  {
    slug: "temp-email-for-coupon-sites",
    title: "How to Get Coupons Without the Spam: Use Temporary Email",
    description: "Unlock coupon codes and deals on discount sites without flooding your inbox with daily promotions and spam.",
    date: "2026-04-09",
    readTime: "5 min read",
    category: "Guide",
    categoryColor: "primary",
    icon: "bi-ticket-perforated",
    tags: ["coupons", "deals", "spam", "shopping"],
  },
  {
    slug: "temp-email-for-job-applications",
    title: "Should You Use Temporary Email for Job Applications?",
    description: "Understand when temporary email is appropriate for job boards, applications, and networking—and when you should use a permanent address.",
    date: "2026-04-12",
    readTime: "6 min read",
    category: "Guide",
    categoryColor: "primary",
    icon: "bi-briefcase",
    tags: ["jobs", "careers", "recruitment", "privacy"],
  },
  {
    slug: "temp-email-for-craigslist",
    title: "How to Use Temporary Email for Craigslist Safely",
    description: "Protect your privacy on Craigslist by using temporary email for listings, inquiries, and account creation.",
    date: "2026-04-14",
    readTime: "5 min read",
    category: "Security",
    categoryColor: "warning",
    icon: "bi-list",
    tags: ["classifieds", "privacy", "listings", "security"],
  },
  {
    slug: "temp-email-for-discord",
    title: "How to Use Temporary Email for Discord Account Creation",
    description: "Create Discord accounts securely with temporary email to test accounts, avoid tracking, or keep multiple identities separate.",
    date: "2026-04-16",
    readTime: "5 min read",
    category: "Guide",
    categoryColor: "primary",
    icon: "bi-chat-dots",
    tags: ["discord", "gaming", "verification", "privacy"],
  },
  {
    slug: "how-to-use-temp-email-for-free-trials",
    title: "How to Use Temporary Email for Free Trials Without Spam",
    description: "Use temporary email for trials, coupons, and one-time signups without turning your main inbox into a marketing dump.",
    date: "2026-04-17",
    readTime: "5 min read",
    category: "Guide",
    categoryColor: "primary",
    icon: "bi-gift",
    tags: ["free trials", "spam", "subscriptions"],
  },
  {
    slug: "temp-email-vs-email-alias",
    title: "Temp Email vs Email Alias: Which Protects Privacy Better?",
    description: "Compare disposable inboxes and email aliases so you can choose the right tool for shopping, trials, and long-term accounts.",
    date: "2026-04-15",
    readTime: "6 min read",
    category: "Comparison",
    categoryColor: "info",
    icon: "bi-shuffle",
    tags: ["alias", "privacy", "comparison"],
  },
  {
    slug: "why-websites-block-disposable-email",
    title: "Why Websites Block Disposable Email Addresses",
    description: "Learn why some sites reject temp mail domains and what alternatives work when you still want privacy during signup.",
    date: "2026-04-13",
    readTime: "5 min read",
    category: "Security",
    categoryColor: "warning",
    icon: "bi-shield-exclamation",
    tags: ["deliverability", "signups", "domains"],
  },
  {
    slug: "temp-email-for-online-shopping",
    title: "How Temporary Email Helps You Shop Online Without Spam",
    description: "Separate receipts from marketing blasts and reduce tracking by using temporary email for online stores and flash sales.",
    date: "2026-04-11",
    readTime: "4 min read",
    category: "Privacy",
    categoryColor: "success",
    icon: "bi-cart3",
    tags: ["shopping", "spam", "retail"],
  },
  {
    slug: "tech-behind-disposable-emails",
    title: "The Tech Behind Disposable Emails",
    description: "Understand how disposable email services work under the hood — from SMTP servers to privacy-first ephemeral storage.",
    date: "2026-03-10",
    readTime: "5 min read",
    category: "Technology",
    categoryColor: "primary",
    icon: "bi-cpu",
    tags: ["SMTP", "privacy", "infrastructure"],
  },
  {
    slug: "receive-sms-otp-online",
    title: "How to Receive SMS OTP Verification Online",
    description: "Discover safe and reliable methods to receive OTPs online without exposing your personal phone number.",
    date: "2026-03-18",
    readTime: "4 min read",
    category: "Privacy",
    categoryColor: "success",
    icon: "bi-shield-lock",
    tags: ["OTP", "SMS", "verification"],
  },
  {
    slug: "private-domains-temp-email",
    title: "Private Domains: Get Your Own Temporary Email",
    description: "Learn how to set up a private custom domain for disposable email and take full control of your online identity.",
    date: "2026-04-02",
    readTime: "6 min read",
    category: "Guide",
    categoryColor: "info",
    icon: "bi-globe2",
    tags: ["domain", "custom email", "setup"],
  },
  {
    slug: "burner-email-for-social-media",
    title: "Why You Need a Burner Email for Social Media",
    description: "Protect your digital identity and stop spam by using burner emails when signing up on social platforms.",
    date: "2026-04-10",
    readTime: "3 min read",
    category: "Security",
    categoryColor: "warning",
    icon: "bi-incognito",
    tags: ["social media", "spam", "anonymity"],
  },
];

export const articles = articleCatalog.slice().sort((left, right) => {
  return new Date(right.date) - new Date(left.date);
});
